# Generated by Django 5.2.7 on 2025-11-06 09:50

import Main.utils
import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_category', models.CharField(help_text='The category of the vehicle (eg: Car, Truck, Bus).', max_length=20, verbose_name='Vehicle Category')),
            ],
        ),
        migrations.CreateModel(
            name='Modsinfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('uploaded_on', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ModImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Main.utils.image_directory_path, verbose_name='Image File')),
                ('slot', models.CharField(choices=[('MAIN', 'Main Image'), ('THUMB1', 'Thumbnail 1'), ('THUMB2', 'Thumbnail 2'), ('THUMB3', 'Thumbnail 3')], max_length=10, verbose_name='Image Slot')),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Main.modsinfo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('mod', 'slot'), name='unique_mod_slot')],
            },
        ),
    ]
