# Generated by Django 5.2.7 on 2025-11-06 12:18

import Main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modsinfo',
            name='img_1',
            field=models.ImageField(blank=True, upload_to=Main.utils.image_directory_path, verbose_name='Image_1'),
        ),
        migrations.AddField(
            model_name='modsinfo',
            name='img_2',
            field=models.ImageField(blank=True, upload_to=Main.utils.image_directory_path, verbose_name='Image_2'),
        ),
        migrations.AddField(
            model_name='modsinfo',
            name='img_3',
            field=models.ImageField(blank=True, upload_to=Main.utils.image_directory_path, verbose_name='Image_3'),
        ),
        migrations.AddField(
            model_name='modsinfo',
            name='thumbnail_img',
            field=models.ImageField(default='img/default_placeholder.jpg', upload_to=Main.utils.image_directory_path, verbose_name='Thumbnail_Image'),
        ),
        migrations.DeleteModel(
            name='ModImage',
        ),
    ]
