# Generated by Django 5.2.7 on 2025-11-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_modsinfo_img_1_modsinfo_img_2_modsinfo_img_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modsinfo',
            name='download_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
