# Generated by Django 5.2.7 on 2025-11-08 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_modsinfo_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modsinfo',
            name='uploaded_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
