# Generated by Django 5.2.7 on 2025-11-10 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_modsinfo_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modsinfo',
            name='uploaded_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
