# Generated by Django 5.2.7 on 2025-11-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_modsinfo_uploaded_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='modsinfo',
            name='downloads_count',
            field=models.IntegerField(default=0),
        ),
    ]
