# Generated by Django 5.2.7 on 2025-11-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_alter_modsinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modsinfo',
            name='downloads_count',
        ),
    ]
