# Generated by Django 5.2.7 on 2025-11-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_remove_modsinfo_downloads_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='modsinfo',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
