# Generated by Django 5.2.7 on 2025-11-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_modsinfo_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='modsinfo',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
