# Generated by Django 5.2.7 on 2025-11-17 02:14

import Main.utils
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_modsinfo_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modsinfo',
            name='img_1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, quality=-1, scale=None, size=[1280, 720], upload_to=Main.utils.image_directory_path, verbose_name='Image_1'),
        ),
        migrations.AlterField(
            model_name='modsinfo',
            name='img_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, quality=-1, scale=None, size=[1280, 720], upload_to=Main.utils.image_directory_path, verbose_name='Image_2'),
        ),
        migrations.AlterField(
            model_name='modsinfo',
            name='img_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=False, quality=-1, scale=None, size=[1280, 720], upload_to=Main.utils.image_directory_path, verbose_name='Image_3'),
        ),
        migrations.AlterField(
            model_name='modsinfo',
            name='thumbnail_img',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='img/default_placeholder.jpg', force_format=None, keep_meta=False, quality=-1, scale=None, size=[1280, 720], upload_to=Main.utils.image_directory_path, verbose_name='Thumbnail_Image'),
        ),
    ]
