# Generated by Django 5.2.7 on 2025-11-22 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_alter_modsinfo_img_1_alter_modsinfo_img_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_type', models.CharField(help_text='The type of the mod(eg: Maps,Skin,Routes).', max_length=20, verbose_name='Mod Type')),
            ],
        ),
        migrations.AddField(
            model_name='modsinfo',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.modtype'),
        ),
    ]
