# Generated by Django 5.2.7 on 2026-03-07 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_alter_modsinfo_img_1_alter_modsinfo_img_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_category', models.CharField(default=None, help_text='The Category of the mod(eg: Maps,Skin,Routes).', max_length=20, verbose_name='Mod Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_category',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(default=None, help_text='The Type of the vehicle (eg: Car, Truck, Bus).', max_length=20, verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='modsinfo',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.modcategory'),
        ),
        migrations.DeleteModel(
            name='Modtype',
        ),
    ]
