# Generated by Django 5.2.7 on 2026-03-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_modcategory_remove_vehicle_vehicle_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modcategory',
            name='mod_category',
            field=models.CharField(default=None, help_text='The Category of the mod(eg: Maps,Skin,Routes).', max_length=20, verbose_name='Mod Categories'),
        ),
    ]
