# Generated by Django 5.2.7 on 2026-03-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_alter_modcategory_mod_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modcategory',
            name='mod_category',
            field=models.CharField(default=None, help_text='The Category of the mod(eg: Maps,Skin,Routes).', max_length=20, verbose_name='Mod Category'),
        ),
    ]
