# Generated by Django 5.2.7 on 2026-03-07 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_alter_modcategory_mod_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modsinfo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.modcategory'),
        ),
        migrations.AlterField(
            model_name='modsinfo',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.vehicle'),
        ),
    ]
