# Generated by Django 5.2.7 on 2026-03-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_alter_modsinfo_category_alter_modsinfo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modcategory',
            name='mod_category',
            field=models.CharField(default='', help_text='The Category of the mod(eg: Maps,Skin,Routes).', max_length=20, verbose_name='Mod Category'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(default='', help_text='The Type of the vehicle (eg: Car, Truck, Bus).', max_length=20, verbose_name='Vehicle Type'),
        ),
    ]
